//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.23 at 01:51:45 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://localhost:8081/hotels", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package choice.university.ivan.schemas;
